server:
  port: 10020
spring:
  application:
    name: authservice
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://192.168.0.106:3306/account_service?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: Qpmz1397
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
